package Models;

import Utils.DatabaseController;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

import javax.persistence.*;
import java.util.Date;

@Entity
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //@Column(name="id")
    private int id; //id is generated by the DB (do not set it)

    private String passwordHint;

    private String password;

    private String image;

    private String username;

    private String fullname;

    @Generated(GenerationTime.INSERT)
    private Date creationDate; //creationDate is generated by the DB (do not set it)

    private boolean isAdmin;

    public User() {};

    public User(String username, String password, String passwordHint, String fullName, String image, boolean isAdmin) {
        this.username = username;
        this.password = password;
        this.passwordHint = passwordHint;
        this.fullname = fullName;
        this.image = image;
        this.isAdmin = isAdmin;
    }

    public void editUser(String username, String password, String passwordHint, String fullName, String image, boolean isAdmin) {
        this.username = username;
        this.password = password;
        this.passwordHint = passwordHint;
        this.fullname = fullName;
        this.image = image;
        this.isAdmin = isAdmin;
    }

    public void setUsername(String text) {
        this.username = text;
    }

    public String getUsername() {
        return username;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getPasswordHint() {
        return passwordHint;
    }

    public void setPasswordHint(String text) {
        this.passwordHint = text;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String text) {
        this.image = image;
    }

    public boolean isAdmin() {
        return isAdmin;
    }

    public void setAdmin(boolean admin) {
        isAdmin = admin;
    }

    public String getFullname() {
        return fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPassword(){return this.password;}

    public boolean equals(User user) {
        System.out.println("I AM CHECKING IT");
        System.out.println("this:"+id);
        System.out.println("other:"+user.getId());
        if(user==null) {
            return false;
        }
        return id == user.getId();
    }

    //DB CRUD
    public void save() {
        DatabaseController.createRecord(this);
    }

    public void update() {
        DatabaseController.updateRecord(this);
    }

    public void delete() {
        DatabaseController.deleteRecord(this.id, User.class);
    }

    static public User load(int id) {
        return (User) DatabaseController.getRecord(id, User.class);
    }

    public String toString() {
    return "[USER: "+id+"] "+fullname+" ("+username+")";
    }

    //DB get by username and password
    public static User login(String username, String password) {
        return DatabaseController.getUserByUsernamePassword(username,password);
    }
    public static String getPasswordHint(String username) {
        return DatabaseController.getUserHint(username);
    }
}


